<a href="https://colab.research.google.com/github/JunetzMasihBelajar/2025_AI_TI1B/blob/main/Jobsheet02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jobsheet 2: Operasi matematika, Vektor, Matriks dan Tipe Data

## 1. Operasi Matematika menggunakan python


### a. Mendapatkan nilai minimum dan maksimum

In [1]:
x = min(5, 10, 25)
y = max(6, 12, 18)
print(x)
print(y)

5
18


### b. Mendapatkan nilai absolut

In [3]:
x = abs(-7.25)
print(x)

7.25


### c. Mendapatkan nilai pangkat

In [4]:
import math
x = math.pow(4, 3)
print(x)

64.0


### d. Mendapatkan nilai akar

In [5]:
import math
x = math.sqrt(64)
print(x)

8.0


### e. Mendapatkan nilai pembulatan

In [6]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)
print(x)
print(y)

2
1


### f. Mendapatkan nilai konstanta

In [8]:
import math
x = math.pi
print(x)

3.141592653589793


## 2. Menggunakan fungsi MATH


In [9]:
import math

a = math.sin(45)
b = math.cos(90)
c = math.tan(180)
d = math.log(8)
e = math.log10(60)
f = math.degrees(2)
x = (1, 2)
y = (4, 6)
g = math.dist(x,y)
h = math.factorial(5)
i = math.fmod(10, 3)
j = math.isnan(float('nan'))
k = math.gamma(5)
l = math.perm(5, 2)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)
print(k)
print(l)


0.8509035245341184
-0.4480736161291701
1.3386902103511544
2.0794415416798357
1.7781512503836436
114.59155902616465
5.0
120
1.0
True
24.0
20


## 3. Operasi Matriks dan vektor dengan python

### a. Membuat matriks di python

In [10]:
import numpy as np
A = np.array([[80, 30, 25],
[50, 20, 10]])
B = np.array([[30, 60, 15],
[10, 30, 30]])

hasil = A + B
print(hasil)

[[110  90  40]
 [ 60  50  40]]


### b. Melakukan operasi dot product

In [11]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)
print(hasil)

2025


### c. Melakukan operasi cross product

In [12]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

Hasil = np.cross(A, B)
print(Hasil)

[-305 -110  350]


# TUGAS PRAKTIKUM

In [16]:
import numpy as np

A = np.array([[3, 1],
              [2, 0]])

B = np.array([[2, 1],
              [1, -1]])

C = np.array([[-1, 1, 2],
              [2, 0, -1]])

AxB = np.dot(A, B)
BxC = np.dot(B, C)

print("Matriks A:")
print(A)

print("\nMatriks B:")
print(B)

print("\nMatriks C:")
print(C)

print("\nHasil A × B:")
print(AxB)

print("\nHasil B × C:")
print(BxC)

Matriks A:
[[3 1]
 [2 0]]

Matriks B:
[[ 2  1]
 [ 1 -1]]

Matriks C:
[[-1  1  2]
 [ 2  0 -1]]

Hasil A × B:
[[7 2]
 [4 2]]

Hasil B × C:
[[ 0  2  3]
 [-3  1  3]]


In [17]:
import math


x = math.factorial(6)
print("6! =", x)


y = math.factorial(8) / math.factorial(5)
print("8! / 5! =", y)


6! = 720
8! / 5! = 336.0


In [18]:
import numpy as np

A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

length_A = np.linalg.norm(A)
length_B = np.linalg.norm(B)


dot_product = np.dot(A, B)

cross_product = np.cross(A, B)

print("Panjang Vektor A:", length_A)
print("Panjang Vektor B:", length_B)
print("Hasil Perkalian Titik A . B:", dot_product)
print("Hasil Perkalian Silang A × B:\n", cross_product)


Panjang Vektor A: 9.1104335791443
Panjang Vektor B: 12.409673645990857
Hasil Perkalian Titik A . B: 58
Hasil Perkalian Silang A × B:
 [ 24  79 -51]
